name: test-win32-mingw64
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:

permissions:
  contents: read

jobs:
  perl:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: configure
        run: perl Makefile.PL
      - name: build
        run: gmake
      - name: test
        run: gmake test
