name: test-linux

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:

permissions:
  contents: read

jobs:
  perl:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        perl: ['5.16', '5.32', 'latest']
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: show Perl configuration
        run: perl -V
      - name: configure
        run: perl Makefile.PL
      - name: build
        run: make
      - name: test
        run: make test

  distribution:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: latest
      - name: configure
        run: perl Makefile.PL
      - name: distribution test
        run: make disttest
